# -*- coding: utf-8 -*-
"""HandwritingRecognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xzxBYX20QijQ8MiOO6WIiH6vU_RiPpI8
"""



"""Dataset - Tensorflow built-in MNIST"""

import tensorflow as tf
# YOUR CODE SHOULD START HERE

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('acc')>0.99):
      print("\nReached 99% accuracy so cancelling training!")
      self.model.stop_training = True

# YOUR CODE SHOULD END HERE

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
# YOUR CODE SHOULD START HERE

x_train = x_train/255.0
x_test = x_test/255.0

callbacks = myCallback()

# YOUR CODE SHOULD END HERE
model = tf.keras.models.Sequential([
# YOUR CODE SHOULD START HERE

  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(512, activation=tf.nn.softmax)
    
# YOUR CODE SHOULD END HERE
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# YOUR CODE SHOULD START HERE

model.fit(x_train, y_train, epochs=10, callbacks=[callbacks])

# YOUR CODE SHOULD END HERE